#server:
#  port: 9000
#
#spring:
#  application:
#    name: API-GATEWAY
#
#  cloud:
#    gateway:
#      server:
#        webflux:
#          routes:
#
#            # AUTH SERVICE
#            - id: authService
#              uri: lb://AUTH-SERVICE
#              predicates:
#                - Path=/auth/**
#
#            # PRODUCT SERVICE
#            - id: productService
#              uri: lb://PRODUCT-SERVICE
#              predicates:
#                - Path=/product/**


server:
  port: 9000

spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      server:
        webflux:
          routes:

            - id: authService
              uri: lb://AUTH-SERVICE
              predicates:
                - Path=/auth/**

            - id: productService
              uri: lb://PRODUCT-SERVICE
              predicates:
                - Path=/product/**

                - id: orderService
                  uri: lb://ORDER-SERVICE
                  predicates:
                    - Path=/product/**
#              filters:







